socket_server:
  host: 0.0.0.0
  port: 8080
  to: asr

asr:
  model_size: large-v2
  no_speech_max_prob: 0.9
  get_speech_segments: false
  decoding_options:
    language: fr
    fp16: true
    sample_len: 20
    temperature: 0.0
    prompt: ~
  context_type: buffer     # prefix, buffer, ~
  context_options:
    buffer_size: 10
#    prefix_size_ratio: 1.0
#    prefix_text: true
  to: socket_server